/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: "ap-southeast-2",
	aws_appsync_graphqlEndpoint: "https://vaicpskrdfgcbhamy67zfepvbe.appsync-api.ap-southeast-2.amazonaws.com/graphql",
	aws_appsync_region: "ap-southeast-2",
	aws_appsync_authenticationType: "API_KEY",
	aws_appsync_apiKey: "da2-3taetqkdarcljfgydbsbgqgjnq",
	aws_cognito_identity_pool_id: "ap-southeast-2:77167389-cfa0-46ea-ae48-cef769cc8fc0",
	aws_cognito_region: "ap-southeast-2",
	aws_user_pools_id: "ap-southeast-2_eXUnXszF3",
	aws_user_pools_web_client_id: "32birgb2l2ec4d6d697rljeer1",
	oauth: {},
	aws_cognito_login_mechanisms: ["EMAIL"],
	aws_cognito_signup_attributes: ["EMAIL"],
	aws_cognito_mfa_configuration: "OFF",
	aws_cognito_mfa_types: ["SMS"],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: []
	},
	aws_user_files_s3_bucket: "msgbucket192251-dev",
	aws_user_files_s3_bucket_region: "ap-southeast-2",
	aws_dynamodb_all_tables_region: "ap-southeast-2",
	aws_dynamodb_table_schemas: [
		{
			tableName: "messagesText-dev",
			region: "ap-southeast-2"
		}
	]
};

export default awsmobile;
